# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitSecrets < Formula
  desc ""
  homepage "https://github.com/benammann/homebrew-tap"
  version "0.1.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/benammann/git-secrets/releases/download/v0.1.3/git-secrets_0.1.3_Darwin_x86_64.tar.gz"
      sha256 "af4cc4236f04251fe8a65f04c811fa79fc7e227914c2df38d5d652cfeb7c9dda"

      def install
        bin.install "git-secrets"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/benammann/git-secrets/releases/download/v0.1.3/git-secrets_0.1.3_Darwin_arm64.tar.gz"
      sha256 "fbce77c89252fdc5cdf6c4b5685882e1561100bc3538dc603943a77ec5d17f9e"

      def install
        bin.install "git-secrets"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/benammann/git-secrets/releases/download/v0.1.3/git-secrets_0.1.3_Linux_arm64.tar.gz"
      sha256 "417d2eb6cf828f513c16098a8922d88fbcfbe8edde02f6574d65c4326194bf5a"

      def install
        bin.install "git-secrets"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/benammann/git-secrets/releases/download/v0.1.3/git-secrets_0.1.3_Linux_x86_64.tar.gz"
      sha256 "3a47057033039011c8af586cbea6dd637c1535e2a47f5318a92701b95d94fa01"

      def install
        bin.install "git-secrets"
      end
    end
  end
end
