# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitSecrets < Formula
  desc ""
  homepage "https://github.com/benammann/homebrew-tap"
  version "0.0.5"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/benammann/git-secrets/releases/download/v0.0.5/git-secrets_0.0.5_Darwin_arm64.tar.gz"
      sha256 "f96a6a730f8d71f619c2789e52691fb7de8a0ddc6a41c9c895e7cca707fba2cb"

      def install
        bin.install "git-secrets"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/benammann/git-secrets/releases/download/v0.0.5/git-secrets_0.0.5_Darwin_x86_64.tar.gz"
      sha256 "3e527acf3e6c36514d28dd4adedf440076dd5311ce00442403d479af774b1d00"

      def install
        bin.install "git-secrets"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/benammann/git-secrets/releases/download/v0.0.5/git-secrets_0.0.5_Linux_arm64.tar.gz"
      sha256 "281b548df6f7f4a5cf1fcb7a49424ff0c8c173207fba334930d4abdded7d439b"

      def install
        bin.install "git-secrets"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/benammann/git-secrets/releases/download/v0.0.5/git-secrets_0.0.5_Linux_x86_64.tar.gz"
      sha256 "b8b6175a42652f77c281b51c7caf04df2beec07ebd001f0785cd26154ea4d893"

      def install
        bin.install "git-secrets"
      end
    end
  end
end
